version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SMTP_EMAIL=${SMTP_EMAIL:-your-email@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-your-app-password}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - PROPERTY_ADDRESS=${PROPERTY_ADDRESS:-123 Luxury Lane, Downtown District, NY 10001}
      - PROPERTY_NAME=${PROPERTY_NAME:-Luxury Apartments at Main Street}
      - LEASING_OFFICE_PHONE=${LEASING_OFFICE_PHONE:-(555) 123-4567}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development services (use with --profile dev)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - SMTP_EMAIL=${SMTP_EMAIL:-your-email@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-your-app-password}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - PROPERTY_ADDRESS=${PROPERTY_ADDRESS:-123 Luxury Lane, Downtown District, NY 10001}
      - PROPERTY_NAME=${PROPERTY_NAME:-Luxury Apartments at Main Street}
      - LEASING_OFFICE_PHONE=${LEASING_OFFICE_PHONE:-(555) 123-4567}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    profiles:
      - dev

  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    profiles:
      - dev
